name: Report PR build failed
on:
  workflow_call:
    inputs:
      number:
        required: true
        type: number
      pr-author:
        required: true
        type: string
jobs:
  assign-and-ping:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check CI status
        id: ci-check
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            const latestCheck = data.check_runs[0];
            return latestCheck.conclusion === 'success';

      - name: Assign pull request to yourself
        if: steps.ci-check.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignResponse = await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.repo.owner],
            });

      - name: Request code review
        if: steps.ci-check.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requestReviewResponse = await github.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [context.repo.owner],
            });
  report-pr-build-failed:
    continue-on-error: true
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Report the build failed
        uses: jungwinter/comment@v1
        with:
          type: create
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ inputs.number }}
          body: |
            Hi, @${{ inputs.pr-author }}! I'm afraid the CI check for PR #${{ inputs.number }} has failed!  
            Don't worry, it'll run again if you commit any changes to this PR.
      - name: Label PR as "CI failed"
        uses: actions/labeler@v4
        with:
          sync-label: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
